### ISSUE TITLE
Turn Off manually

### ISSUE THREAD

**Issue by boxman0617** [philschatz/fetch-vcr#18]
Is there a way to turn off fetch-vcr for some urls? If there isn't, is this something that could be considered?

**Comment by philschatz** [comment]
Unfortunately, there is not currently a way to turn off `fetch-vcr` for some URLs but that would be a great feature to have!

If you would like to try and add it, here are some places that might be useful:

- https://github.com/philschatz/fetch-vcr/blob/master/lib/index.js#L20 to add a `urlWhiteList` or `urlBlackList` regular expression
- https://github.com/philschatz/fetch-vcr/blob/master/lib/index.js#L184 maybe change the conditions to additionally check if the URL matches the white/black list

**Comment by boxman0617** [comment]
I'll submit a PR soon!
